# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.20.164339'

RELEASE_GIT_HEAD = 'def24c97e046ba0b895a2fdb22acc30f8a4bc0d3'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'dem0nx309/yt-dlp'

ORIGIN = 'dem0nx309/yt-dlp'

_pkg_version = '2024.01.20.164339'
